# Lesson 10

In [22]:
# PRZYKŁAD 1: Instalacja i import NumPy

# Instalacja NumPy (w Google Colab już zainstalowany)
# !pip install numpy
# Import NumPy - konwencja 'np'

import numpy as np
# Sprawdzenie wersji
print(f"Wersja NumPy: {np.__version__}")
# Wynik: Wersja NumPy: 1.24.3 (lub nowsza)
# Informacje o konfiguracji NumPy
np.show_config()

Wersja NumPy: 2.4.4
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35225",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.4",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35225",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.31.188.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ucojyb64/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/in

In [28]:
# PRZYKŁAD 2: Listy vs Tablice NumPy - porównanie wydajności

import numpy as np
import time

# Tworzenie dużej listy Pythonowej
python_list = list(range(1000000))

# Tworzenie tablicy NumPy
numpy_array = np.array(range(1000000))

# Test 1: Podwojenie wszystkich elementów - LISTA
start = time.time()
doubled_list = [x * 2 for x in python_list]
list_time = time.time() - start
print(f"Czas dla listy Python: {list_time:.4f} s")

# Test 2: Podwojenie wszystkich elementów - NUMPY
start = time.time()
doubled_array = numpy_array * 2
numpy_time = time.time() - start
print(f"Czas dla tablicy NumPy: {numpy_time:.4f} s")

# Porównanie
speedup = list_time / numpy_time
print(f"\nNumPy jest {speedup:.1f}x szybszy!")

# Porównanie rozmiaru w pamięci
import sys
list_size = sys.getsizeof(python_list)
array_size = numpy_array.nbytes
print(f"\nRozmiar listy: {list_size / 1024:.1f} KB")
print(f"Rozmiar tablicy NumPy: {array_size / 1024:.1f} KB")
print(f"Oszczędność pamięci: {(1 - array_size/list_size)*100:.1f}%")


Czas dla listy Python: 0.0729 s
Czas dla tablicy NumPy: 0.0029 s

NumPy jest 24.9x szybszy!

Rozmiar listy: 7812.6 KB
Rozmiar tablicy NumPy: 7812.5 KB
Oszczędność pamięci: 0.0%


In [24]:
# PRZYKŁAD 3: Tworzenie tablic NumPy - różne sposoby

import numpy as np

# 1. Z listy Pythonowej
arr_from_list = np.array([1, 2, 3, 4, 5])
print("Z listy:", arr_from_list)
print("Typ:", type(arr_from_list))
print("Dtype:", arr_from_list.dtype) # int64 na większości systemów

# 2. Z zagnieżdżonej listy (tablica 2D)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\nTablica 2D:\n", arr_2d)
print("Shape:", arr_2d.shape) # (2, 3) - 2 wiersze, 3 kolumny
print("Wymiary:", arr_2d.ndim) # 2 - dwuwymiarowa

# 3. Tablice wypełnione zerami
zeros = np.zeros(5)
print("\nZera:", zeros)
zeros_2d = np.zeros((3, 4)) # 3 wiersze, 4 kolumny
print("Zera 2D:\n", zeros_2d)

# 4. Tablice wypełnione jedynkami
ones = np.ones((2, 3))
print("\nJedynki:\n", ones)

# 5. Tablice wypełnione konkretną wartością
full = np.full((2, 2), 7)
print("\nWypełnione 7:\n", full)

# 6. Sekwencje - podobne do range()
sequence = np.arange(0, 10, 2) # start, stop, step
print("\nSekwencja:", sequence) # [0 2 4 6 8]

# 7. Równoodległe wartości
linspace = np.linspace(0, 1, 5) # 5 wartości od 0 do 1
print("Linspace:", linspace) # [0. 0.25 0.5 0.75 1. ]

# 8. Macierz identyczności
identity = np.eye(3)
print("\nMacierz identyczności:\n", identity)

# 9. Losowe wartości
random_vals = np.random.rand(5) # 5 losowych wartości [0, 1)
print("\nLosowe [0,1):", random_vals)
random_ints = np.random.randint(1, 100, size=10) # 10 losowych int z [1,100)
print("Losowe int:", random_ints)

# 10. Określanie typu danych
float_array = np.array([1, 2, 3], dtype=np.float32)
print("\nFloat32:", float_array, float_array.dtype)

Z listy: [1 2 3 4 5]
Typ: <class 'numpy.ndarray'>
Dtype: int64

Tablica 2D:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Wymiary: 2

Zera: [0. 0. 0. 0. 0.]
Zera 2D:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Jedynki:
 [[1. 1. 1.]
 [1. 1. 1.]]

Wypełnione 7:
 [[7 7]
 [7 7]]

Sekwencja: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]

Macierz identyczności:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Losowe [0,1): [0.5675762  0.75958277 0.71012301 0.84527575 0.54381472]
Losowe int: [56 51 76 36 88  8 38 53 74  4]

Float32: [1. 2. 3.] float32


In [ ]:
# 